---
- name: Validate qsvc_phase
  ansible.builtin.assert:
    that:
      - qsvc_phase in ['template', 'appvm']
    fail_msg: "'qsvc_phase' must be 'template' or 'appvm'."

- name: Run template phase
  ansible.builtin.import_tasks: template.yml
  when: qsvc_phase == 'template'

- name: Run AppVM phase
  ansible.builtin.import_tasks: appvm.yml
  when: qsvc_phase == 'appvm'
