---
galaxy_info:
  author: Frederic Pierret
  description: Configure split-SSH vault qube.
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
    - name: Debian
      versions: [all]
  galaxy_tags:
    - qubes
    - qubesos
    - split_ssh
    - vault
dependencies: []
