---
- name: Validate qsvc_name and qubes list
  ansible.builtin.assert:
    that:
      - qsvc_name | length > 0
      - qsvc_dom0_qubes is sequence
      - qsvc_dom0_qubes is not string
    fail_msg: >-
      'qsvc_name' and 'qsvc_dom0_qubes' (a list) are required.

- name: Enable qubes-service "{{ qsvc_name }}" on each qube
  qubesos.core.qube:
    name: "{{ item }}"
    state: present
    services:
      - "{{ qsvc_name }}"
  loop: "{{ qsvc_dom0_qubes }}"
  loop_control:
    label: "{{ item }}"
