---
galaxy_info:
  author: Frederic Pierret
  description: Install per-agent socat forwarder services and default-agent file in a client qube.
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Fedora
      versions: [all]
    - name: Debian
      versions: [all]
  galaxy_tags:
    - qubes
    - qubesos
    - splitssh
    - client
dependencies: []
