---
- name: Gather OS family
  ansible.builtin.setup:
    gather_subset: min

- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"
      skip: true

- name: Install split-SSH client packages
  ansible.builtin.package:
    name: "{{ split_ssh_packages }}"
    state: present
  when: split_ssh_packages | length > 0

- name: Install /etc/profile.d/qubes-ssh.sh helper
  ansible.builtin.copy:
    src: qubes-ssh.sh
    dest: /etc/profile.d/qubes-ssh.sh
    owner: root
    group: root
    mode: "0644"

- name: Create /usr/lib/split-ssh directory
  ansible.builtin.file:
    path: /usr/lib/split-ssh
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install split-ssh-forwarder start script
  ansible.builtin.template:
    src: start-ssh-forwarder.j2
    dest: /usr/lib/split-ssh/start-forwarder
    owner: root
    group: root
    mode: "0755"

- name: Install split-ssh-forwarder templated systemd unit
  ansible.builtin.copy:
    src: split-ssh-forwarder@.service
    dest: /usr/lib/systemd/system/split-ssh-forwarder@.service
    owner: root
    group: root
    mode: "0644"
