---
- name: Install split-ssh package in vault template
  ansible.builtin.package:
    name: "{{ split_ssh_packages }}"
    state: present

- name: Seed /etc/skel/.ssh
  ansible.builtin.file:
    path: /etc/skel/.ssh
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Seed /etc/skel/.ssh/identities.d
  ansible.builtin.file:
    path: /etc/skel/.ssh/identities.d
    state: directory
    owner: root
    group: root
    mode: "0700"
